local mod = get_mod("rwaon_talents")

mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/1h_axes_shield")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/1h_hammers_shield")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/2h_axes_wood_elf")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/kerillian_waywatcher_career_skill")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/longbows")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/repeating_crossbows_elf")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/shortbows_hagbane")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/shortbows")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/sienna_scholar_career_skill")
--mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/staff_blast_beam")
--mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/staff_spark_spear")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/staff_fireball_fireball")
mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/staff_fireball_geiser")
--mod:dofile("scripts/mods/rwaon_talents/scripts/settings/equipment/weapon_templates/staff_flamethrower")